---
# PostgreSQL installation

# - set_fact:
#     distro_packages: "{{ base_apt_packages }} + [ 'libreadline6' ]"
#   when: ansible_distribution_release != 'bionic'
#
# - set_fact:
#     distro_packages: "{{ base_apt_packages }} + [ 'libreadline7' ]"
#   when: ansible_distribution_release == 'bionic'

- name: Ensure the needed APT packages are present
  apt:
    name:
      - tar
      - gzip
      - build-essential
      - curl
      - make
      - gcc
      - zlib1g-dev
      - libperl-dev
      - libpython-dev
      - libssl-dev
      - libreadline-dev
      - libsystemd-dev
    update_cache: true
    cache_valid_time: 600

- name: Ensure the postgresql user is created
  user:
    name: "{{ postgresql_user}}"
    shell: /bin/bash
    create_home: true

- name: Ensure the src dir is created
  file:
    path: "{{ postgresql_src_dir }}"
    state: directory
    owner: "{{ postgresql_user}}"
    group: "{{ postgresql_user}}"
    mode: 0755

- name: Ensure postgresql tmp dir is created
  file:
    path: "{{ postgresql_tmp_dir }}"
    state: directory
    mode: 0755
    owner: "{{ postgresql_user}}"
    group: "{{ postgresql_user}}"

- name: Get postgresql source code
  unarchive:
    src: "https://ftp.postgresql.org/pub/source/v{{ postgresql_version }}/postgresql-{{ postgresql_version }}.tar.gz"
    dest: "{{ postgresql_tmp_dir }}"
    owner: "{{ postgresql_user}}"
    group: "{{ postgresql_user}}"
    remote_src: true
    extra_opts:
     - --strip=1

- name: Configure postgresql source install
  command: ./configure {{ postgresql_config_params }} --prefix={{ postgresql_src_dir }} --with-openssl --with-systemd
  args:
    chdir: "{{ postgresql_tmp_dir }}"
    creates: "{{ postgresql_tmp_dir }}/GNUmakefile"


# - name: Make postgresql source install
#   command: make world -j4 chdir=/usr/local/src/postgresql-{{ postgresql_version }}
#   args:
#     creates: /usr/local/src/postgresql-{{ postgresql_version }}/src/bin/psql/psql
#
# - name: Install postgresql from built source
#   command: make install-world chdir=/usr/local/src/postgresql-{{ postgresql_version }}
#   args:
#     creates: /pg/postgresql-{{ postgresql_version }}/bin/psql

# - name: list postgresql binaries
#   command: ls -1 /pg/postgresql-{{ postgresql_version }}/bin
#   register: postgresql_binaries
#   changed_when: false
#   tags: postgresql-installation

# - name: add postgresql binaries to alternatives
#   alternatives: name={{ item }} path=/pg/postgresql-{{ postgresql_version }}/bin/{{ item }} link=/usr/bin/{{ item }}
#   with_items: postgresql_binaries.stdout_lines
#   tags: postgresql-installation
