---
# tasks file for ansible-role-postgresql

- name: Check if postgresql is installed
  command: "{{ postgresql_src_dir }}/bin/postgres --version"
  changed_when: false
  failed_when: false
  register: psql_check_cmd

- name: Decide whether or not install PostgreSQL
  set_fact:
    postgresql_install: "{% if psql_check_cmd.rc == 0 %}false{% else %}true{% endif %}"

- name: Notify about existing PostgreSQL installation
  debug:
    msg: >
      Another PostgreSQL is already
      present - {{ psql_check_cmd.stdout }}
  when: not postgresql_install

- include: install.yml
  when: postgresql_install

- include: configure.yml

- name: Ensure the postgresql service is started
  service:
    name: postgresql
    state: started
  when:
    - postgresql_configure_systemd
    - postgresql_start_service

- name: Ensure postgresql intall tmp dir is absent
  file:
    path: "{{ postgresql_tmp_dir }}"
    state: absent
